```{r}
######
library(DESeq2)
#library(caret)
library(pheatmap)
library(colorspace)
#library(VennDiagram)
library(readxl)
library(RColorBrewer)
library(colorspace)
library(umap)
library(gridExtra)
library(ggplotify)
library(ggplot2)
library(patchwork)
library(plotly)
library(circlize)
library(ComplexHeatmap)
library(dendextend)
```

```{r}
## Load files
# Change directory where files are stored from Deseq2 analysis
setwd(file.path("Data"))

#colclasses = c("numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric")

canon <- read.csv2("IPA_canon_7comp.csv", header = TRUE, sep = ";", row.names = 1, dec = ",")#, colClasses = colclasses)
zscore <- read.csv("IPA_zscore_7comp.csv", header = TRUE, sep = ";", row.names = 1, dec = ",")#, colClasses = colclasses)
# Read File with pathways categories
szscore <- read.csv("IPA_zscore_all_split_A_D.csv", header = TRUE, sep = ";", row.names = 1)

```
```{r}
# Conver to numeric the columns
#canon [] <- lapply(canon, function(x) gsub(",", ".", x))
# Conver to numeric the columns
#zscore [] <- lapply(zscore , function(x) gsub(",", ".", x))
```





```{r}
# By ranking on rowsums of pathways
filter_pathways <- function(canon_df, zscore_df, threshold_significance = 100, threshold_directionality = 0.5) {
  # Convert comma-separated numeric values to numeric format
  for (col in names(canon_df)) {
    canon_df[[col]] <- as.numeric(gsub(",", ".", canon_df[[col]]))
  }
  # Calculate row sums of canon_df to rank pathways
  pathway_ranks <- rowSums(canon_df, na.rm = TRUE)
  
  # Select top pathways based on threshold_significance
  top_pathways <- names(head(sort(pathway_ranks, decreasing = TRUE), threshold_significance))
  
  # Find pathways with directionality higher than absolute value of threshold_directionality in zscore_df
  directionality_condition <- apply(abs(zscore_df[top_pathways,]) > threshold_directionality, 1, any, na.rm = TRUE)
  
  # Combine the two conditions to get the final set of pathways
  selected_pathways <- top_pathways[directionality_condition]
  
  return(selected_pathways)
}
```

```{r}
# Check rownames from both dataframes
all(row.names(zscore) == row.names(canon))
head(canon)
head(zscore)

```

```{r}
#Define column names
#colnames_clusters <- c("IOX0.3 vs C", "IOX1 vs C", "T vs C", "T+IOX.3 vs C", "T+IOX1 vs C")# For 5 comparisons
colnames_clusters <- c("IOX0.3 vs C", "IOX1 vs C", "T vs C", "T+IOX.3 vs C", "T+IOX1 vs C", "T+IOX.3 vs T", "T+IOX1 vs T")# For 7 comparisons
```

```{r}
# Change column names
# Reset colnames of both dataframes with gene module names
colnames(canon) <- colnames_clusters
colnames(zscore)<- colnames_clusters
colnames(canon)==colnames(zscore)
```
```{r}
#Check dimensions
dim(canon)
dim(zscore)
```

```{r}
# FIlter by classified pathways
selected_pathways <- rownames(szscore)
# Filter canon
canon2 <- canon[selected_pathways,]
canon2

# Filter Zscore
zscore2 <- zscore[selected_pathways,]
zscore2

```




```{r}
# Filter pathways
selected_pathways <- filter_pathways(canon2, zscore2, threshold_significance = 25, threshold_directionality = 0.5)

```


```{r}
# Filter canon
canon2 <- canon[selected_pathways,]
canon2

# Filter Zscore
zscore2 <- zscore[selected_pathways,]
zscore2


# Filter szscore
szscore <- szscore[selected_pathways,]
szscore
```
```{r}
zscore2["HIF1 alpha Signaling",]
```


```{r}
# Ensure szscore$Group is a factor
szscore$Group <- factor(szscore$Group)
```

```{r}
# Assign custom colors to factor levels
vec_col <- szscore$Group
vec_col
table(vec_col)
col_fun = colorRamp2(c(-4, 0, 4), c("blue", "white", "red"))
col_mechanisms <- list("A" = "A: Fibrosis",
                       "B" = "B: Lipid Metabolism",
                       "C" = "C: Inflammation",
                       "D" = "D: Other")
```

```{r}
# Larger font size pathways
bigger_pathways <- c("Assembly of collagen fibrils and other multimeric structures",
                      "IL-17A Signaling in Fibroblasts",
                      "Extracellular matrix organization",
                      "Collagen biosynthesis and modifying enzymes",
                      "IL-6 Signaling",
                      "Hepatic Fibrosis Signaling Pathway",
                      "HIF1 alpha Signaling")

```


```{r}
# Define row names cex vector
rownames_cex <- ifelse(rownames(zscore2) %in% bigger_pathways, 1.1, 1)#0.87, 0.8
rownames_cex
```
```{r}
# Define colors for each sector
sector_colors <- c("black", "deepskyblue3", "darkblue", "darkorange3")
# Repeat each color for the number of rows in each sector
names(sector_colors) <- unique(vec_col)  # Assign colors to unique classes
# Assign colors to row names based on vec_col
sector_row_colors <- sector_colors[vec_col]
```





```{r}
## Circular Heatmap
## Clear
circos.clear()
graphics.off()
```


```{r}

#Change directory where files are stored from Deseq2 analysis
#setwd(file.path("Output", "IPA analysis"))
pdf("Ingenuity Pathway Analysis on DEGs from in vitro stimulations (IOX2 & TGFβ1)_Fig4_7_comparisons_new.pdf", width = 14, height = 15, pointsize = 12)

# Define parameters
start_degree <- 90
gap_degree <- c(4, 4, 4, 15)
track_margin <- c(0, 0)
legend_title_directionality <- "Directionality"
legend_title_mechanisms <- "Mechanisms"

# Circular Heatmap
circos.par(
  start.degree = start_degree,
  gap.degree = gap_degree,
  track.margin = track_margin
)

# Legend
legend_directionality <- Legend(
  title = legend_title_directionality,
  col_fun = col_fun,
  grid_height = unit(8, "mm"),
  grid_width = unit(8, "mm"),
  labels_gp = gpar(fontsize = 14),
  title_gp = gpar(fontsize = 16)
)
legend_mechanisms <- Legend(
  title = legend_title_mechanisms,
  col_mechanisms,
  grid_height = unit(8, "mm"),
  grid_width = unit(8, "mm"),
  labels_gp = gpar(fontsize = 14),
  title_gp = gpar(fontsize = 16)
)
# Set row names
rownames(zscore2) <- factor(rownames(zscore2))

# Circular Heatmap
circos_ht <- circos.heatmap(
  zscore2,
  split = vec_col,
  col = col_fun,
  cluster = TRUE,
  rownames.side = "inside",
  cell.border = "black",
  bg.lwd = 1,
  bg.lty = 1,
  cell.lwd = 0.5,
  track.height = 0.12,#0.15 for 7 comparisons
  show.sector.labels = TRUE,
  dend.side = "outside",
  dend.track.height = 0.1,
  rownames.cex = rownames_cex,
  cell.lty = 1,
  bg.border = "gray50",
  rownames.font = par("font"),
  rownames.col = sector_row_colors,
)

# Adding a new track for column labels
circos.track(
  track.index = get.current.track.index() + 1,
  panel.fun = function(x, y) {
    if (CELL_META$sector.numeric.index == 4) { # the last sector
      column_names <- colnames(zscore2)
      num_columns <- length(column_names)
      ## Change the order of the rownames
      column_names <- rev(column_names)
      
      circos.text(
        rep(CELL_META$cell.xlim[2], num_columns) + convert_x(2, "mm"),
        1:num_columns - 0.2,
        column_names,
        cex = 0.75,
        adj = c(0, 0.9),
        facing = "inside"
      )
    }
  },
  bg.border = NA
)

# Adjust the size of the title
par(cex = 1.3)


# Draw legends
draw(legend_directionality, x = unit(0.90, "npc"), y = unit(0.90, "npc"), just = c("right", "top"))
draw(legend_mechanisms, x = unit(0.20, "npc"), y = unit(0.90, "npc"), just = c("right", "top"))



# Add title with modified coordinates
title("Ingenuity Pathway Analysis on DEGs from in vitro stimulations (IOX2 & TGFβ1)", 
      xlab = "", ylab = "", line = -2)

dev.off()

```

```{r}
## Circular Heatmap
## Clear
circos.clear()
graphics.off()
```




```{r}
# Change directory where files are stored from Deseq2 analysis
# setwd(file.path("Output", "IPA analysis"))
tiff("Ingenuity Pathway Analysis on DEGs from in vitro stimulations (IOX2 & TGFβ1)_Fig4_7_comparisons_new.tiff", width = 14, height = 15, units = "in", res = 300)


# Define parameters
start_degree <- 90
gap_degree <- c(4, 4, 4, 15)
track_margin <- c(0, 0)
legend_title_directionality <- "Directionality"
legend_title_mechanisms <- "Mechanisms"

# Circular Heatmap
circos.par(
  start.degree = start_degree,
  gap.degree = gap_degree,
  track.margin = track_margin
)

# Legend
legend_directionality <- Legend(
  title = legend_title_directionality,
  col_fun = col_fun,
  grid_height = unit(8, "mm"),
  grid_width = unit(8, "mm"),
  labels_gp = gpar(fontsize = 14),
  title_gp = gpar(fontsize = 16)
)
legend_mechanisms <- Legend(
  title = legend_title_mechanisms,
  col_mechanisms,
  grid_height = unit(8, "mm"),
  grid_width = unit(8, "mm"),
  labels_gp = gpar(fontsize = 14),
  title_gp = gpar(fontsize = 16)
)

# Set row names
rownames(zscore2) <- factor(rownames(zscore2))

# Circular Heatmap
circos_ht <- circos.heatmap(
  zscore2,
  split = vec_col,
  col = col_fun,
  cluster = TRUE,
  rownames.side = "inside",
  cell.border = "black",
  bg.lwd = 1,
  bg.lty = 1,
  track.height = 0.12,#0.15 for 7 comparisons, 0.12 for 5 comparisons
  cell_width = 0.01,
  show.sector.labels = TRUE,
  dend.side = "outside",
  dend.track.height = 0.1,
  rownames.cex = rownames_cex,
  bg.border = "gray50",
  rownames.font = par("font"),
  rownames.col = sector_row_colors
)

circos.track(track.index = get.current.track.index(), panel.fun = function(x, y) {
  xlim = get.cell.meta.data("xlim")
  ylim = get.cell.meta.data("ylim")
  circos.rect(xlim[1], (ylim[1]+ylim[2])/2, xlim[2], (ylim[1]+ylim[2])/2, col = "white")
}, bg.border = NA)

# Adding a new track for column labels
circos.track(
  track.index = get.current.track.index() + 1,
  panel.fun = function(x, y) {
    if (CELL_META$sector.numeric.index == 4) { # the last sector
      column_names <- colnames(zscore2)
      num_columns <- length(column_names)
      ## Change the order of the rownames
      column_names <- rev(column_names)
      
      circos.text(
        rep(CELL_META$cell.xlim[2], num_columns) + convert_x(2, "mm"),
        1:num_columns - 0.2,
        column_names,
        cex = 0.75,
        adj = c(0, 0.9),
        facing = "inside"
      )
    }
  },
  bg.border = NA
)

# Adjust the size of the title
par(cex = 1.5)


# Draw legends
draw(legend_directionality, x = unit(0.90, "npc"), y = unit(0.90, "npc"), just = c("right", "top"))
draw(legend_mechanisms, x = unit(0.20, "npc"), y = unit(0.90, "npc"), just = c("right", "top"))



# Add title with modified coordinates
title("Ingenuity Pathway Analysis on DEGs from in vitro stimulations (IOX2 & TGFβ1)", 
      xlab = "", ylab = "", line = -2)

dev.off()

```

